---
title: "Highchart to Docx"
format: docx
execute:
  echo: false
  message: false
  warning: false
---

```{r setup}
#| include: false

# Libraries ----
library(tidyverse)
library(scales)
library(janitor)
library(highcharter)
library(webshot2)

# Color palette ----
locality_pal <- c("#193CBC", "#589ACF", "#FAC484")
```

### Children Living below Poverty Threshold

```{r}
# Set data
df <- read_csv("../data/child_poverty.csv") %>% 
  mutate(locality = case_when(county_fips == "003" ~ "Albemarle",
                              county_fips == "540" ~ "Charlottesville",
                              county_fips == "000" ~ "Virginia"))

df$percent <- df$pct_child_pov
df$label <- df$locality 
df$count_label <- prettyNum(df$num_child_pov, big.mark = ",")

title <- "Percent of Children Living below the Poverty Threshold"
ytext <- "Percent of Children"

```

```{r series-percent, results = 'asis'}

df <- df %>% filter(year >= 2010)

series_percent_chart <- df %>% 
  mutate(percent = round(percent,0)) %>% 
  hchart("line", hcaes(x = year, y = percent, group = label)) %>% 
  hc_legend(align = "center", verticalAlign = "top") %>%
  hc_xAxis(title = list(enabled = FALSE), labels = list(allowOverlap = TRUE, step = 1, style = list(fontSize = '1.2em'))) %>%
  hc_yAxis(min = 0, max = 100,
           title = list(text = ytext),
           labels = list(format = '{text}%')) %>%
  hc_colors(locality_pal) %>%
  hc_plotOptions(series = list(dataLabels = list(format = '{y: f}%', enabled = TRUE)),
                 line = list( marker = list(enabled = TRUE) )) %>%
  hc_tooltip(formatter = JS("function(){
  return '<b>' + this.key + '</b></br>' + this.series.name + ': <b>' + this.y + '%</b></br>' + 'Est. Number Experiencing this Outcome: <b>' + this.point.count_label + '</b>'
  }")) %>%
  hc_title(text = title,
           align = 'left') %>%
  # hc_subtitle(text = '2018-2023',
  #             align = "left",
  #             style = list(fontSize = '1.4em')) %>%
  # hc_caption(text = source_acs_range,
  #            align = "right",
  #            style = list(fontSize = '1em')) %>%
  hc_add_theme(hc_theme_smpl())

series_percent_chart

```